/* 관리자 정보 */
CREATE TABLE `ADMINISTRATOR` (
  `ID`		VARCHAR(20)							NOT NULL PRIMARY KEY ,
  `NAME`	VARCHAR(20)							NOT NULL,
  `NICK`	VARCHAR(20)		DEFAULT ''			NOT NULL,
  `PW`		VARCHAR(60)							NOT NULL,
  `PW_PREV`	VARCHAR(60)		DEFAULT ''			NOT NULL,

  `PERMITION_NO`	INT(3)	DEFAULT 0	NOT NULL,

  `EMAIL`	VARCHAR(99)		DEFAULT ''			NOT NULL,
  `TEL`		VARCHAR(13)		DEFAULT ''			NOT NULL,
  `FAX`		VARCHAR(13)		DEFAULT ''			NOT NULL,
  `MOBILE`	VARCHAR(13)		DEFAULT ''			NOT NULL,
  `ZIPCODE`	CHAR(5)			DEFAULT '00000'		NOT NULL,
  `ADDRESS`	VARCHAR(50)		DEFAULT ''			NOT NULL,
  `ADDRESS_EXT`	VARCHAR(50)	DEFAULT ''			NOT NULL,

  `STATUS`			ENUM('활성','제한','비활성') 
						DEFAULT '활성'	NOT NULL,
  `JOIN_DATE`		DATETIME			NOT NULL,
  `LOGIN_DATE`		DATETIME			NOT NULL,
  `PW_DATE`			DATETIME			NOT NULL,


  INDEX `INDEX_ADMINISTRATOR` (`PW`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/* 최고 관리자 정보 입력 */
INSERT INTO ADMINISTRATOR (ID,NAME,PW,JOIN_DATE,LOGIN_DATE,PW_DATE) VALUES ('admin','관리자','1111',NOW(),NOW(),NOW());

/* 권한 정보 */
CREATE TABLE `ADMINISTRATOR_PERMITION` (
  `IDX`			INT(3) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `TITLE`		VARCHAR(20)		NOT NULL,
  `CONTENTS`	TEXT		NOT NULL,
  `STATUS`		ENUM('Y','N') DEFAULT 'Y' NOT NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


/* 회원 */
CREATE TABLE `MEMBER` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `ID`					VARCHAR(50)				DEFAULT ''			NOT NULL,
  `LEVEL`				ENUM('일반','파트너')		DEFAULT '일반'		NOT NULL,
  `NAME`				VARCHAR(40)				DEFAULT ''			NOT NULL,
  `EMAIL`				VARCHAR(50)				DEFAULT ''			NOT NULL,
  `PW`					VARCHAR(50)				DEFAULT ''			NOT NULL,
  `PW_DATE`				DATETIME									NULL,
  `PROFILE_IMAGE`		VARCHAR(200)			DEFAULT ''			NOT NULL,
  `BIRTHDAY`			DATE										NULL,

  `TEL`					VARCHAR(11)				DEFAULT ''			NOT NULL,
  `TEL_CERTIFY`			DATE										NULL,
  `TEL_SAFE`			VARCHAR(12)				DEFAULT ''			NOT NULL,

  `MILEAGE`				INT(10) UNSIGNED		DEFAULT 0			NOT NULL,

  `ACCEPT_TERMS`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `ACCEPT_PRIVACY`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `ACCEPT_MARKETING`	ENUM('Y','N')			DEFAULT 'N'			NOT NULL,

  `RECEIVE_TEL`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `RECEIVE_SMS`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `RECEIVE_PUSH`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `RECEIVE_EMAIL`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,

  `RECEIVE_TEL_DATE`	DATETIME									NULL,
  `RECEIVE_SMS_DATE`	DATETIME									NULL,
  `RECEIVE_PUSH_DATE`	DATETIME									NULL,
  `RECEIVE_EMAIL_DATE`	DATETIME									NULL,

  `REMARK`				VARCHAR(2000)			DEFAULT ''			NOT NULL,

  `CERTIFY`				ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `SESSION_ID`			VARCHAR(50)				DEFAULT ''			NOT NULL,

  `FCM`					VARCHAR(250)			DEFAULT ''			NOT NULL,
  `IP`					VARCHAR(15)				DEFAULT '0.0.0.0'	NOT NULL,

  `JOIN_DATE`			DATETIME				DEFAULT NOW()		NOT NULL,
  `LOGIN_DATE`			DATETIME									NULL,
  `LOGIN_CNT`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL,
  `STATUS`				ENUM('휴면','정상','정지','퇴출','탈퇴','탈퇴신청')			DEFAULT '정상'			NOT NULL,
  
  INDEX `INDEX_MEMBER` (`PW`,`ID`,`NAME`,`TEL`,`MILEAGE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


/* 탈퇴 회원 */
CREATE TABLE `MEMBER_DROP` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `ID`					VARCHAR(50)				DEFAULT ''			NOT NULL,
  `LEVEL`				ENUM('일반','파트너')		DEFAULT '일반'		NOT NULL,
  `NAME`				VARCHAR(40)				DEFAULT ''			NOT NULL,
  `EMAIL`				VARCHAR(50)				DEFAULT ''			NOT NULL,
  `PW`					VARCHAR(50)				DEFAULT ''			NOT NULL,
  `PW_DATE`				DATETIME									NULL,
  `PROFILE_IMAGE`		VARCHAR(200)			DEFAULT ''			NOT NULL,
  `BIRTHDAY`			DATE										NULL,

  `TEL`					VARCHAR(11)				DEFAULT ''			NOT NULL,
  `TEL_CERTIFY`			DATE										NULL,
  `TEL_SAFE`			VARCHAR(12)				DEFAULT ''			NOT NULL,

  `MILEAGE`				INT(10) UNSIGNED		DEFAULT 0			NOT NULL,

  `ACCEPT_TERMS`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `ACCEPT_PRIVACY`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `ACCEPT_MARKETING`	ENUM('Y','N')			DEFAULT 'N'			NOT NULL,

  `RECEIVE_TEL`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `RECEIVE_SMS`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `RECEIVE_PUSH`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,
  `RECEIVE_EMAIL`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL,

  `RECEIVE_TEL_DATE`	DATETIME									NULL,
  `RECEIVE_SMS_DATE`	DATETIME									NULL,
  `RECEIVE_PUSH_DATE`	DATETIME									NULL,
  `RECEIVE_EMAIL_DATE`	DATETIME									NULL,

  `REMARK`				VARCHAR(2000)			DEFAULT ''			NOT NULL,

  `IP`					VARCHAR(15)				DEFAULT '0.0.0.0'	NOT NULL,

  `JOIN_DATE`			DATETIME				DEFAULT NOW()		NOT NULL,
  `LOGIN_DATE`			DATETIME									NULL,
  `LOGIN_CNT`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL,
  `DROP_DATE`			DATETIME				DEFAULT NOW()		NOT NULL,
  
  INDEX `INDEX_MEMBER_DROP` (`ID`,`NAME`,`TEL`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


/* 회원SNS */
CREATE TABLE `MEMBER_SNS` (
  `MEMBER_NO`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL PRIMARY KEY,

  `SNS`					VARCHAR(10)				DEFAULT ''			NOT NULL,
  `ID`					VARCHAR(50)				DEFAULT ''			NOT NULL,
  `DATA`				VARCHAR(1000)			DEFAULT ''			NOT NULL,
  `LOGIN_DATE`			DATETIME				DEFAULT NOW()		NOT NULL,
  `IP`					VARCHAR(15)				DEFAULT '0.0.0.0'	NOT NULL,

  INDEX `INDEX_MEMBER_SNS` (`SNS`,`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `MOBILE_AUTH` (
  `TEL`					VARCHAR(11)				DEFAULT ''				NOT NULL PRIMARY KEY,
  `AUTH_NUMBER`			VARCHAR(10)				DEFAULT ''				NOT NULL,
  `INPUT_DATE`			DATETIME				DEFAULT NOW()			NOT NULL,
  `EXPIRE_DATE`			DATETIME										NOT NULL,
  
  INDEX `INDEX_MOBILE_AUTH` (`AUTH_NUMBER`,`EXPIRE_DATE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;




/* 게시판 */
CREATE TABLE `BOARD` (
  `IDX`					INT(10) UNSIGNED							NOT NULL PRIMARY KEY COMMENT '인덱스',
  `BBSCODE`				VARCHAR(15)									NOT NULL COMMENT '게시판 고유 코드',
  `SEQ`					INT(10) UNSIGNED		DEFAULT 1			NOT NULL COMMENT '순서',
  `DEPTH`				INT(2) UNSIGNED			DEFAULT 0			NOT NULL COMMENT '깊이',
  `FATHER_NO`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL COMMENT '상위 인덱스',
  `CATEGORY_NO`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL COMMENT '분류 인덱스',
  `MEMBER_NO`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL COMMENT '회원 인덱스',
  `NAME`				VARCHAR(20)				DEFAULT ''			NOT NULL COMMENT '글쓴이',
  `PW`					VARCHAR(50)				DEFAULT ''			NOT NULL COMMENT '비밀번호',
  `NOTICE`				ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '공지여부',

  `EMAIL`				VARCHAR(255)			DEFAULT ''			NOT NULL COMMENT '메일주소',
  `URL`					VARCHAR(255)			DEFAULT ''			NOT NULL COMMENT '대표URL',

  `HIT`					INT(10) UNSIGNED		DEFAULT 0			NOT NULL COMMENT '조회수',
  `COMMENT`				INT(10) UNSIGNED		DEFAULT 0			NOT NULL COMMENT '댓글 갯수',

  `LINK`				VARCHAR(4000)			DEFAULT ''			NOT NULL COMMENT '링크 목록',
  `FILE`				VARCHAR(4000)			DEFAULT ''			NOT NULL COMMENT '업로드 파일 목록',
  `IMG`					VARCHAR(100)			DEFAULT ''			NOT NULL COMMENT '대표 이미지',
  `IP`					VARCHAR(15)				DEFAULT '0.0.0.0'	NOT NULL COMMENT '글쓴 IP',

  `TITLE`				VARCHAR(200)			DEFAULT ''			NOT NULL COMMENT '제목',
  `CONTENTS`			TEXT										NOT NULL COMMENT '내용',

  `TYPE`				ENUM('일반','비밀','공지')	DEFAULT '일반'		NOT NULL COMMENT '게시 종류',
  `STATUS`				ENUM('Y','N','DELETE')	DEFAULT 'Y'			NOT NULL COMMENT '게시 여부',
  `FINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '최초작성시간',
  `LINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '최종수정시간',

  INDEX `INDEX_BOARD` (`BBSCODE`,`SEQ`,`DEPTH`,`TITLE`,`NAME`,`MEMBER_NO`,`NOTICE`,`TYPE`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci  COMMENT='게시판';

CREATE TABLE `BOARD_CATEGORY` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `BBSCODE`				VARCHAR(15)									NOT NULL	COMMENT '게시판 고유 코드',
  `SEQ`					INT(10)	UNSIGNED		DEFAULT 1			NOT NULL	COMMENT '정렬 순서',
  `TITLE`				VARCHAR(20)				DEFAULT ''			NOT NULL	COMMENT '분류명',
  `STATUS`				ENUM('Y','N','DELETE')	DEFAULT 'Y'			NOT NULL	COMMENT '노출 여부',
  
  INDEX `INDEX_BOARD_CATEGORY` (`BBSCODE`,`SEQ`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='게시판 분류';

/* 코멘트 */
CREATE TABLE `BOARD_COMMENTS` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `BOARD_NO`			INT(10) UNSIGNED							NOT NULL COMMENT '게시글 인덱스',
  `MEMBER_NO`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL COMMENT '회원 인덱스',
  `NAME`				VARCHAR(20)				DEFAULT ''			NOT NULL COMMENT '글쓴이',
  `PW`					VARCHAR(50)				DEFAULT ''			NOT NULL COMMENT '비밀번호',
  `CONTENTS`			TEXT										NOT NULL COMMENT '내용',
  `TYPE`				ENUM('일반','비밀','공지')	DEFAULT '일반'		NOT NULL COMMENT '게시 종류',
  `STATUS`				ENUM('Y','N','DELETE')	DEFAULT 'Y'			NOT NULL COMMENT '게시 여부',
  `FINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '최초작성시간',
  `LINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '최종수정시간',

  INDEX `INDEX_BOARD_COMMENTS` (`BOARD_NO`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='게시판 코멘트';

/* 게시판 환경설정 */
CREATE TABLE `BOARD_CONFIGURATION` (
  `BBSCODE`				VARCHAR(15)									NOT NULL PRIMARY KEY COMMENT '게시판 고유 코드',
  `TITLE`				VARCHAR(30)									NOT NULL COMMENT '게시판명',
  `STATUS`				ENUM('Y','N','DELETE')	DEFAULT 'Y'			NOT NULL COMMENT '사용 여부',
  `USE_CATEGORY`		ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '분류 사용',
  `USE_REPLY`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '댓글 사용',
  `USE_COMMENT`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '코멘트 사용',
  `USE_UPLOAD`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '파일업로드 사용',
  `USE_LINK`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT 'URL링크 사용',
  `USE_COVER`			ENUM('Y','N')			DEFAULT 'N'			NOT NULL COMMENT '커버이미지 사용',
  `COVER_W`				INT(4) UNSIGNED			DEFAULT 100			NOT NULL COMMENT '커버이미지 너비px',
  `COVER_H`				INT(4) UNSIGNED			DEFAULT 80			NOT NULL COMMENT '커버이미지 높이px',
  `PASSWORD`			VARCHAR(50)				DEFAULT ''			NOT NULL COMMENT '게시판 입장 비밀번호',
  `PAGING_ROW`			INT(3) UNSIGNED			DEFAULT 20			NOT NULL COMMENT '목록 글 수',
  `PAGING_NUM`			INT(2) UNSIGNED			DEFAULT 9			NOT NULL COMMENT '페이징 갯수',
  `DAY_NEW`				INT(2) UNSIGNED			DEFAULT 7			NOT NULL COMMENT '새로운 글 일 수',
  `PDS_NUM`				INT(3) UNSIGNED			DEFAULT 9			NOT NULL COMMENT '파일 업로드 갯수',
  `PDS_MAXBYTE`			INT(4) UNSIGNED			DEFAULT 3			NOT NULL COMMENT '파일당 최대 업로드 크기MB',
  `PERMIT_WRITE`		ENUM('관리자','회원그룹','특별회원','회원','비회원') 
												DEFAULT '관리자'		NOT NULL COMMENT '쓰기 권한',
  `PERMIT_LIST`			ENUM('관리자','회원그룹','특별회원','회원','비회원') 
												DEFAULT '비회원'		NOT NULL COMMENT '목록보기 권한',
  `PERMIT_VIEW`			ENUM('관리자','회원그룹','특별회원','회원','비회원') 
												DEFAULT '비회원'		NOT NULL COMMENT '내용보기 권한',
  `PERMIT_REPLY`		ENUM('관리자','회원그룹','특별회원','회원','비회원') 
												DEFAULT '관리자'		NOT NULL COMMENT '댓글 권한',
  `PERMIT_COMMENT`		ENUM('관리자','회원그룹','특별회원','회원','비회원') 
												DEFAULT '관리자'		NOT NULL COMMENT '코멘트 권한',
  `SPECIAL_MEMBER`		TEXT										NULL COMMENT '특별회원 목록',
  `REG_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '생성 일시',
  `REMARK`				VARCHAR(4000)			DEFAULT ''			NOT NULL COMMENT '비고',

  INDEX `INDEX_BOARD_CONFIGURATION` (`TITLE`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='게시판 환경설정';


/* FAQ */
CREATE TABLE `FAQ` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `CATEGORY_NO`			INT(10) UNSIGNED		DEFAULT 1			NOT NULL COMMENT '분류 인덱스',
  `SEQ`					INT(10) UNSIGNED		DEFAULT 1			NOT NULL COMMENT '순서',
  `TITLE`				VARCHAR(400)			DEFAULT ''			NOT NULL COMMENT '질문',
  `CONTENTS`			TEXT										NOT NULL COMMENT '답변내용',
  `STATUS`				ENUM('Y','N')			DEFAULT 'Y'			NOT NULL COMMENT '노출 여부',
  `FINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '생성 일시',
  `LINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '수정 일시',
  
  INDEX `INDEX_FAQ` (`CATEGORY_NO`,`SEQ`,`STATUS`,`TITLE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='자주묻는 질문';


/* FAQ 분류 */
CREATE TABLE `FAQ_CATEGORY` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `LANGUAGE`			VARCHAR(3)				DEFAULT 'KR'		NOT NULL COMMENT '언어',
  `SEQ`					INT(10) UNSIGNED		DEFAULT 1			NOT NULL COMMENT '순서',
  `FATHER_NO`			INT(10) UNSIGNED		DEFAULT 0			NOT NULL COMMENT '상위 분류 인덱스',

  `TITLE`				VARCHAR(200)			DEFAULT ''			NOT NULL COMMENT '분류명',
  `STATUS`				ENUM('N','Y')			DEFAULT 'Y'			NOT NULL COMMENT '노출 여부',
  `REG_DATE`			DATETIME				DEFAULT NOW()		NOT NULL COMMENT '생성일', 

  INDEX `INDEX_FAQ_CATEGORY` (`LANGUAGE`,`STATUS`,`SEQ`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='자주묻는 질문 분류';


/* Q & A */
CREATE TABLE `QNA` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',

  `CONTENTS_NO`			INT(10) UNSIGNED							NOT NULL COMMENT '컨텐츠 인덱스',
  `MEMBER_NO`			INT(10) UNSIGNED							NOT NULL COMMENT '작성 회원 인덱스',

  `REMARK`				VARCHAR(4000)			DEFAULT ''			NOT NULL	COMMENT '비고',
  `STATUS`				ENUM('Y','N','DELETE')	DEFAULT 'Y'			NOT NULL	COMMENT '상태',
  `CONTENTS`			VARCHAR(4000)			DEFAULT ''			NOT NULL	COMMENT '질문 내용',
  `Q_STATUS`			ENUM('Y','N','DELETE')	DEFAULT 'Y'			NOT NULL	COMMENT '질문 상태',
  `FINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL	COMMENT '등록시간',
  `LINPUT_DATE`			DATETIME				DEFAULT NOW()		NOT NULL	COMMENT '최종수정시간',

  `ANSWER`				VARCHAR(4000)			DEFAULT ''			NOT NULL	COMMENT '답변 내용',
  `ANSWER_STATUS`		ENUM('Y','N','DELETE')	DEFAULT 'N'			NOT NULL	COMMENT '답변 상태',
  `ANSWER_FINPUT_DATE`	DATETIME				DEFAULT				NULL		COMMENT '답변 등록시간',
  `ANSWER_LINPUT_DATE`	DATETIME				DEFAULT				NULL		COMMENT '답변 최종수정시간',

  INDEX `INDEX_QNA` (`CONTENTS_NO`,`MEMBER_NO`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='개별 질문';



/* 결제 */
CREATE TABLE `PAYMENT` (
  `IDX`					INT(10) UNSIGNED								NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `RECEIPT_NUMBER`		VARCHAR(13)				DEFAULT ''				NOT NULL COMMENT '결제 번호',
  `TYPE`				VARCHAR(10)				DEFAULT '예약'			NOT NULL COMMENT '결제 대상',
  `FATHER_NO`			INT(10) UNSIGNED								NOT NULL COMMENT '결제 대상 인덱스',
  `RELATION_NO`			INT(10) UNSIGNED		DEFAULT 0				NOT NULL COMMENT '관련 결제 인덱스',

  `STOCK`				INT(10) UNSIGNED		DEFAULT 1				NOT NULL COMMENT '주문 상품 수',
  `ORDER_STOCK`			INT(10) UNSIGNED		DEFAULT 1				NOT NULL COMMENT '주문 갯수',
  `PAY_METHOD`			VARCHAR(10)				DEFAULT '신용카드'			NOT NULL COMMENT '결제 방식',
  `PAY_PRICE`			INT(10) UNSIGNED		DEFAULT 0				NOT NULL COMMENT '결제 금액',
  `PAY_TOTAL`			INT(10) UNSIGNED		DEFAULT 0				NOT NULL COMMENT '총 결제 금액',
  `AUTH`				VARCHAR(1000)			DEFAULT '[]'			NOT NULL COMMENT 'PG결제 반환 정보 JSON',

  `STATUS`				ENUM('미결제','구매완료','구매관련','취소','사용가능','사용중','부분환불대기','환불대기','부분환불완료','환불완료')	
												DEFAULT '미결제'			NOT NULL COMMENT '결제 상태',
  `PAY_DATE`			DATETIME				DEFAULT NOW()			NOT NULL COMMENT '결제 일자',
  `REFUND_PRICE`		INT(10) UNSIGNED		DEFAULT 0				NOT NULL COMMENT '환불 금액',
  `REFUND_DATE`			DATETIME										NULL COMMENT '환불 일자',
  
  INDEX `INDEX_PAYMENT` (`RECEIPT_NUMBER`,`TYPE`,`STATUS`,`FATHER_NO`,`RELATION_NO`,`PAY_DATE`,`REFUND_DATE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='결제';


/* 배너 */
CREATE TABLE `BANNER` (
  `IDX`			INT(10) UNSIGNED										NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `SEQ`			INT(10) UNSIGNED				DEFAULT 0				NOT NULL COMMENT '순서',
  `DEVICE`		ENUM('PC','모바일','모바일웹','앱','공통')	DEFAULT '공통'		NOT NULL COMMENT '디바이스 종류',
  `TITLE`		VARCHAR(50)						DEFAULT ''				NOT NULL COMMENT '제목',
  `IMG`			VARCHAR(200)					DEFAULT ''				NOT NULL COMMENT '이미지',
  `CONTENTS`	TEXT													NOT NULL COMMENT '본문',

  `START_DATE`	DATETIME												NULL COMMENT '표시 시작 일자',
  `END_DATE`	DATETIME												NULL COMMENT '표시 종료 일자',
  `FINPUT_DATE`	DATETIME						DEFAULT NOW()			NOT NULL COMMENT '등록 일자',
  `LINPUT_DATE`	DATETIME						DEFAULT NOW()			NOT NULL COMMENT '수정 일자',

  `STATUS`		ENUM('Y','N','DELETE')			DEFAULT 'Y'				NOT NULL COMMENT '상태',

  INDEX `INDEX_BANNER` (`DEVICE`,`SEQ`,`START_DATE`,`END_DATE`,`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='배너';


/* 팝업창 */
CREATE TABLE `POPUP` (
  `IDX`			INT(10) UNSIGNED										NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `SEQ`			INT(10) UNSIGNED				DEFAULT 0				NOT NULL COMMENT '순서',
  `DEVICE`		ENUM('PC','모바일','모바일웹','앱','공통')	DEFAULT '공통'		NOT NULL COMMENT '디바이스 종류',
  `TITLE`		VARCHAR(50)						DEFAULT ''				NOT NULL COMMENT '제목',
  `IMG`			VARCHAR(200)					DEFAULT ''				NOT NULL COMMENT '본문 이미지',
  `URL`			VARCHAR(200)					DEFAULT ''				NOT NULL COMMENT '링크 주소',
  `URL_TARGET`	ENUM('새창','셀프')					DEFAULT '셀프'			NOT NULL COMMENT '링크열리는 윈도우',
  `CONTENTS`	TEXT													NOT NULL COMMENT '본문',

  `START_DATE`	DATETIME												NULL COMMENT '표시 시작 일자',
  `END_DATE`	DATETIME												NULL COMMENT '표시 종료 일자',
  `FINPUT_DATE`	DATETIME						DEFAULT NOW()			NOT NULL COMMENT '등록 일자',
  `LINPUT_DATE`	DATETIME						DEFAULT NOW()			NOT NULL COMMENT '수정 일자',

  `STATUS`		ENUM('Y','N','DELETE')			DEFAULT 'Y'				NOT NULL COMMENT '상태',

  INDEX `INDEX_POPUP` (`DEVICE`,`SEQ`,`START_DATE`,`END_DATE`,`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='팝업';


/* 약관 */
CREATE TABLE `TERMS` (
  `IDX`			INT(10) UNSIGNED										NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '인덱스',
  `CATEGORY`	VARCHAR(50)						DEFAULT ''				NOT NULL COMMENT '약관 종류',
  `CONTENTS`	TEXT													NOT NULL COMMENT '본문',

  `REG_DATE`	DATETIME												NULL COMMENT '반영 일자',
  `FINPUT_DATE`	DATETIME						DEFAULT NOW()			NOT NULL COMMENT '등록 일자',
  `LINPUT_DATE`	DATETIME						DEFAULT NOW()			NOT NULL COMMENT '수정 일자',

  `STATUS`		ENUM('Y','N','DELETE')			DEFAULT 'Y'				NOT NULL COMMENT '상태',

  INDEX `INDEX_TERMS` (`CATEGORY`,`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='약관';



/* 공통 비즈톡 템플릿 */
CREATE TABLE `KAKAO_BIZTALK_DEF` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CATEGORY`			ENUM('사용자','모두','관리전용')	
											DEFAULT '사용자'			NOT NULL,
  `TEMPLETE_CODE`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `TEMPLETE`			VARCHAR(40)			DEFAULT ''				NOT NULL,
  `CONTENTS`			VARCHAR(1000)		DEFAULT ''				NOT NULL,

  `BUTTON_1_TYPE`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_1_NAME`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_1_LINK_M`		VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_1_LINK_PC`	VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_1_ANDROID`	VARCHAR(50)			DEFAULT ''				NOT NULL,
  `BUTTON_1_IOS`		VARCHAR(50)			DEFAULT ''				NOT NULL,

  `BUTTON_2_TYPE`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_2_NAME`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_2_LINK_M`		VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_2_LINK_PC`	VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_2_ANDROID`	VARCHAR(50)			DEFAULT ''				NOT NULL,
  `BUTTON_2_IOS`		VARCHAR(50)			DEFAULT ''				NOT NULL,

  `BUTTON_3_TYPE`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_3_NAME`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_3_LINK_M`		VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_3_LINK_PC`	VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_3_ANDROID`	VARCHAR(50)			DEFAULT ''				NOT NULL,
  `BUTTON_3_IOS`		VARCHAR(50)			DEFAULT ''				NOT NULL,

  `BUTTON_4_TYPE`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_4_NAME`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_4_LINK_M`		VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_4_LINK_PC`	VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_4_ANDROID`	VARCHAR(50)			DEFAULT ''				NOT NULL,
  `BUTTON_4_IOS`		VARCHAR(50)			DEFAULT ''				NOT NULL,

  `BUTTON_5_TYPE`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_5_NAME`		VARCHAR(40)			DEFAULT ''				NOT NULL,
  `BUTTON_5_LINK_M`		VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_5_LINK_PC`	VARCHAR(100)		DEFAULT ''				NOT NULL,
  `BUTTON_5_ANDROID`	VARCHAR(50)			DEFAULT ''				NOT NULL,
  `BUTTON_5_IOS`		VARCHAR(50)			DEFAULT ''				NOT NULL,

  `STATUS`				ENUM('N','Y')		DEFAULT 'Y'				NOT NULL,
  `FINPUT_DATE`			DATETIME			DEFAULT NOW()			NOT NULL,
  `LINPUT_DATE`			DATETIME			DEFAULT NOW()			NOT NULL,
  
  INDEX `INDEX_KAKAO_BIZTALK_DEF` (`CATEGORY`,`TEMPLETE`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE `KAKAO_BIZTALK` (
  `IDX`					INT(10) UNSIGNED						NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CONTENTS_NO`			INT(10) UNSIGNED	DEFAULT 0			NOT NULL,
  `BIZTALK_NO`			INT(10) UNSIGNED	DEFAULT 0			NOT NULL,
  `STATUS`				ENUM('N','Y')		DEFAULT 'Y'			NOT NULL,
  
  INDEX `INDEX_KAKAO_BIZTALK` (`CONTENTS_NO`,`BIZTALK_NO`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `KAKAO_BIZTALK_LOG` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `CONTENTS_NO`			INT(10) UNSIGNED	DEFAULT 0				NOT NULL,
  `MEMBER_NO`			INT(10) UNSIGNED	DEFAULT 0				NOT NULL,
  `BIZTALK_NO`			INT(10) UNSIGNED							NOT NULL,
  `MSG_ID`				VARCHAR(20)			DEFAULT ''				NOT NULL,
  `CONTENTS`			VARCHAR(1000)		DEFAULT ''				NOT NULL,

  `RESPONSE_CODE`		VARCHAR(4)			DEFAULT ''				NOT NULL,
  `RESPONSE_MSG`		VARCHAR(200)		DEFAULT ''				NOT NULL,
  `RESPONSE_REMARK`		VARCHAR(200)		DEFAULT ''				NOT NULL,

  `STATUS`				ENUM('성공','실패')		DEFAULT '성공'			NOT NULL,
  `INPUT_DATE`			DATETIME			DEFAULT NOW()			NOT NULL,
  
  INDEX `INDEX_KAKAO_BIZTALK_LOG` (`CONTENTS_NO`,`MEMBER_NO`,`MSG_ID`,`STATUS`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `KAKAO_BIZTALK_SEND` (
  `IDX`					INT(10) UNSIGNED							NOT NULL AUTO_INCREMENT PRIMARY KEY,

  `CONTENTS_NO`			INT(10) UNSIGNED	DEFAULT 0				NOT NULL,
  `MEMBER_NO`			INT(10) UNSIGNED	DEFAULT 0				NOT NULL,
  `BIZTALK_NO`			INT(10) UNSIGNED							NOT NULL,
  `RECEIVER_NUM`		VARCHAR(11)			DEFAULT ''				NOT NULL,
  `MESSAGE`				VARCHAR(1000)		DEFAULT ''				NOT NULL,
  `SEND_VALUES`			TEXT										NOT NULL,

  `TRY_COUNT`			INT(1) UNSIGNED		DEFAULT 1				NOT NULL,

  `INPUT_DATE`			DATETIME			DEFAULT NOW()			NOT NULL
  
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

